# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c144bfc048fc5dd7333eebf8764add0313fc3662f8a27d7f452a5f5a9f6f9d2579d8ca20db8161ec61fddde7452c4720e721ffe3f41724a577c055b86a0aeb
  tumblr_consumer_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n
  tumblr_consumer_secret: OHOp34JLhwtPTJpLf1hqpf1eb3w7SZK6iYSSRWfVs1RPNXd1q6
  tumblr_token: Xd1WIfBGMtu7fZoqGmmK3nFzHDgOMBabCkxTHRVMSO8ViS5AfT
  tumblr_secret: vW0PolSJjCNdzTIKX5xVJ8YiwrgV4pI0DqQDvQhsNTHGZvSMZT
  tumblr_api_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n

test:
  secret_key_base: c08937f0e4525ad4e5c6f90bce11351b71cd0d436a98c773414a97bc8e828b0bbdbffe785dd9c3ea8956701c803dba7f28262cd99692328958cdbf9e0eba2fbb
  tumblr_consumer_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n
  tumblr_consumer_secret: OHOp34JLhwtPTJpLf1hqpf1eb3w7SZK6iYSSRWfVs1RPNXd1q6
  tumblr_token: Xd1WIfBGMtu7fZoqGmmK3nFzHDgOMBabCkxTHRVMSO8ViS5AfT
  tumblr_secret: vW0PolSJjCNdzTIKX5xVJ8YiwrgV4pI0DqQDvQhsNTHGZvSMZT
  tumblr_api_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tumblr_consumer_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n
  tumblr_consumer_secret: OHOp34JLhwtPTJpLf1hqpf1eb3w7SZK6iYSSRWfVs1RPNXd1q6
  tumblr_token: Xd1WIfBGMtu7fZoqGmmK3nFzHDgOMBabCkxTHRVMSO8ViS5AfT
  tumblr_secret: vW0PolSJjCNdzTIKX5xVJ8YiwrgV4pI0DqQDvQhsNTHGZvSMZT
  tumblr_api_key: xb6DbNBfsTDDIq6k5mPB5TuPu8cUtWKte2JmVmVNjLosnF8w0n
